### ISSUE TITLE
Download as image is broken

### ISSUE THREAD

**Issue by flaviasequeira** [designing-experiences/Lush#10]
Download as image is broken.

On Chrome:
1. The image doesn't contain the pictures.
2. There are white gaps between the rows.
3. Downloads as two .png files.

On Safari
Completely broken. The download doesn't contain the blueprint at all.

**Comment by bobvanluijt** [comment]
Related to this issue: https://github.com/designing-experiences/Lush.js/issues/14

**Comment by bobvanluijt** [comment]
Fixed in latest Lush.js release

@flaviasequeira please note that the CDN takes 30 min to refresh. So you can check it 30 min after this commit
